# Use an official OpenJDK runtime as a parent image
FROM openjdk:17-jdk-slim

# Set the working directory inside the container
WORKDIR /app

# Copy the Spring Boot JAR file into the container
COPY eureka-server.jar /app/eureka-server.jar

# Expose the application's port (change this if your app runs on a different port)
EXPOSE 8888

# Define the command to run the application
CMD ["java", "-jar", "/app/eureka-server.jar"]