# Use an official OpenJDK runtime as a parent image
FROM openjdk:17-jdk-slim

# Set the working directory inside the container
WORKDIR /app

# Copy the Spring Boot JAR file into the container
COPY config-server.jar /app/config-server.jar

# Expose the application's port (change this if your app runs on a different port)
EXPOSE 9999

# Define the command to run the application
CMD ["java", "-jar", "/app/config-server.jar"]
